export const ROUTES = {
  root: '/',
  config: '/config',
  configInicial: '/config_inicial',
  login: '/login',
  selectCompany: '/select-company',
  home: '/home',
  dashboardFinanceiro: '/dashboards/financeiro',
  dashboardVendas: '/dashboards/vendas',
  pedidoVenda: '/pedidos-venda',
  pedidoVendaRepresentantes: '/pedidos-venda-representantes',
  pedidoVendaNovo: '/pedidos-venda/novo',
  pedidoVendaEditar: '/pedidos-venda/editar',
  pcpApontamentoProducao: '/pcp/apontamento-producao',
  pcpParadasMaquina: '/pcp/paradas-maquina',
  pcpOrdensFabricacao: '/pcp/ordens-fabricacao',
  pcpPreparacaoMaquina: '/pcp/preparacao-maquina',
  servicoOrdens: '/servico/ordens-servico',
  servicoApontamentoMaoObra: '/servico/apontamento-mao-obra',
  comprasPedidoLiberacao: '/compras/pedido-liberacao',
  basicoClientes: '/basico/clientes',
  segurancaUsuarios: '/seguranca/usuarios',
  segurancaTipoApontamento: '/seguranca/tipo-apontamento',
  segurancaSessoes: '/seguranca/sessoes',
  manutencaoOrdens: '/manutencao/ordens',
  qualidadeFichaProcesso: '/qualidade/ficha-inspecao-processo',
  qualidadeFichaRecebimento: '/qualidade/ficha-inspecao-recebimento',
} as const;
